version: '3.8'

services:
  router_postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: router
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - router_database
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

networks:
  router_database:
    external: true
    name: router_database