---
- hosts: all
  become: yes
  tags: [ dnsmasq ]

  vars:
    router: { hostname: "{{ hostname }}", short_name: "{{ hostname }}", ip: "{{ base_ip }}", mac: "{{ base_mac }}", description: "Home router"}
    current_machines: "{{ other_machines + [ router ] }}"

  tasks:
    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present

    - name: Config dnsmasq
      template:
        src: templates/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf

    - name: Config hosts
      template:
        src: templates/hosts.j2
        dest: /etc/hosts

    - name: "Enable & start the dnsmasq service"
      service:
        name: dnsmasq
        enabled: yes
        state: started
