---
- hosts: all
  tags: [ xarr ]

  tasks:
    - name: "Installing sqlite3 for the config editing"
      apt:
        name: sqlite3
        state: present
      become: true

    - name: Create app dirs
      file:
        path: /home/{{ main_user }}/{{ item.app_name }}
        state: directory
        mode: '0700'
      with_items: "{{ xarr_apps }}"

    - name: "Creating docker-compose for *arr"
      template: 
        src: templates/docker-compose-xarr.yml.j2
        dest: /home/{{ main_user }}/{{ item.app_name }}/docker-compose.yml
      with_items: "{{ xarr_apps }}"

    # Starting then stopping it to generate then make it safe to edit the config / DB
    - name: "Starting *arr"
      docker_compose:
        project_src: /home/{{ main_user }}/{{ item.app_name }}
        state: present
      with_items: "{{ xarr_apps }}"

    - name: "Stopping *arr"
      docker_compose:
        project_src: /home/{{ main_user }}/{{ item.app_name }}
        state: present
        stopped: yes
      with_items: "{{ xarr_apps }}"

    - name: "Generating the sql files"
      template:
        src: templates/xarr-init-scripts.sql.j2
        dest: /home/{{ main_user }}/{{ item.app_name }}/init_cfg.sql
      with_items: "{{ xarr_apps }}"

    - name: "Applying the sql files"
      shell: cat /home/{{ main_user }}/{{ item.app_name }}/init_cfg.sql | sqlite3 /home/{{ main_user }}/{{ item.app_name }}/data/{{ item.app_name }}.db
      with_items: "{{ xarr_apps }}"

    - name: "Removing the sql files"
      file:
        path: /home/{{ main_user }}/{{ item.app_name }}/init_cfg.sql
        state: absent
      with_items: "{{ xarr_apps }}"

    - name: "Enabling authentication"
      lineinfile:
        path: /home/{{ main_user }}/{{ item.app_name }}/data/config.xml
        regexp: '\<AuthenticationMethod\>([a-zA-Z0-9])*\<\/AuthenticationMethod\>'
        line: '<AuthenticationMethod>Forms</AuthenticationMethod>'
      with_items: "{{ xarr_apps }}"
      when: item.edit_config is defined and item.edit_config == True

    - name: "Starting *arr again"
      docker_compose:
        project_src: /home/{{ main_user }}/{{ item.app_name }}
        state: present
        restarted: yes
      with_items: "{{ xarr_apps }}"
