---
- hosts: all
  tags: [ docker ]
  become: yes

  tasks:
    - import_role: { name: 'geerlingguy.docker' }

    - name: Enable docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Setup pip3 for dependencies
      apt:
        name: python3-pip
        state: present

    - name: Install the Docker SDK (Automating docker-compose)
      pip:
        name: [PyYAML, docker, 'docker-compose']
        state: latest
        umask: '0022'
