---
- hosts: all
  tags: [ paperless ]

  tasks:
    - name: Create app dirs
      file:
        path: /opt/docker-apps/paperless
        state: directory
        mode: '0700'

    - name: "Creating docker-compose for paperless"
      template:
        src: files/paperless/docker-compose.yml
        dest: /opt/docker-apps/paperless/docker-compose.yml

    - name: "Starting Paperless"
      docker_compose:
        project_src: /opt/docker-apps/paperless
        state: present
