---
- hosts: all
  tags: [ jellyfin ]

  tasks:
    - name: Create app dirs
      file:
        path: /opt/docker-apps/jellyfin
        state: directory
        mode: '0700'

    - name: "Creating docker-compose for Jellyfin"
      template:
        src: templates/jellyfin/docker-compose.yml.j2
        dest: /opt/docker-apps/jellyfin/docker-compose.yml

    - name: "Starting Jellyfin"
      docker_compose:
        project_src: /opt/docker-apps/jellyfin
        state: present
