---
main_user: oxodao

hostname: router
tld: "lan"
base_url: "{{ hostname }}.{{ tld }}"
base_ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"

ntp_timezone: Europe/Paris

#region Samba shares
smb_shares:
  - short_name: shares
    mount_url: //192.168.1.100/Shares
    username: shares
    password: '{{ SMB_PWD_SHARES }}'
    opts: 'rw'
  - short_name: documents
    mount_url: //192.168.1.100/Documents
    username: documents
    password: '{{ SMB_PWD_DOCUMENTS }}'
    opts: 'rw'
#endregion

other_machines:
  - hostname: 'severusdesk'
    short_name: 'severusdesk'
    ip: '192.168.1.10'
    description: 'Main desktop computer'

  - hostname: 'severusbook'
    short_name: 'severusbook'
    ip: '192.168.1.11'
    description: 'Main laptop (Huawei)'

  - hostname: 'severuspad'
    short_name: 'severuspad'
    ip: '192.168.1.12'
    description: 'Main tablet'

  - hostname: 'nas'
    short_name: 'nas'
    ip: '192.168.1.100'
    description: 'Synology NAS'

  - hostname: 'severusphone'
    short_name: 'op6'
    ip: '192.168.1.13'
    description: 'Main phone'

  - hostname: 'switch'
    short_name: 'switch'
    ip: '192.168.1.14'
    description: 'Main Nintendo Switch'

forwarded_dns_servers:
  - 1.1.1.1
  - 8.8.8.8

#region xarr
xarr_apps:
  - app_name: jackett
    short_name: 'jkt'
    port: 9117
    image: 'lscr.io/linuxserver/jackett'
    config_db: []

  - app_name: sonarr
    short_name: 'srr'
    port: 8989
    image: 'lscr.io/linuxserver/sonarr'
    mount_medias: True
    edit_config: True
    config_db:
      - { key: 'firstdayofweek', value: 1 }
      - { key: 'calendarweekcolumnheader', value: "'ddd DD/MM'" }
      - { key: 'shortdateformat', value: "'YYYY-MM-DD'" }
      - { key: 'longdateformat', value: "'dddd D MMMM YYYY'" }
      - { key: 'timeformat', value: "'HH:mm'" }

  - app_name: radarr
    short_name: 'rrr'
    port: 7878
    image: 'lscr.io/linuxserver/radarr'
    mount_medias: True
    edit_config: True
    config_db:
      - { key: 'firstdayofweek', value: 1 }
      - { key: 'calendarweekcolumnheader', value: "'ddd DD/MM'" }
      - { key: 'shortdateformat', value: "'YYYY-MM-DD'" }
      - { key: 'longdateformat', value: "'dddd D MMMM YYYY'" }
      - { key: 'timeformat', value: "'HH:mm'" }
      - { key: 'movieinfolanguage', value: 2 }
      - { key: 'uilanguage', value: 2 }
#endregion

#region nginx
other_apps:
  - app_name: paperless
    short_name: 'paper'
    port: 8000
  - app_name: jellyfin
    short_name: play
    port: 8096

nginx_apps: "{{ xarr_apps + other_apps }}"
#endregion
