---
main_user: oxodao

hostname: router
tld: "lan"
base_url: "{{ hostname }}.{{ tld }}"
base_ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"

ntp_timezone: Europe/Paris

wireguard_server_port: 48666

#region Samba shares
smb_shares:
  - short_name: shares
    mount_url: //192.168.14.100/Shares
    username: shares
    password: '{{ SMB_PWD_SHARES }}'
    opts: 'rw'
  - short_name: documents
    mount_url: //192.168.14.100/Documents
    username: documents
    password: '{{ SMB_PWD_DOCUMENTS }}'
    opts: 'rw'
#endregion

other_machines:
  - hostname: 'severus'
    short_name: 'severus'
    ip: '192.168.14.10'
    description: 'Main desktop computer'

  - hostname: 'lockhart'
    short_name: 'lockhart'
    ip: '192.168.14.11'
    description: 'Main laptop (Huawei)'

  - hostname: 'remus'
    short_name: 'remus'
    ip: '192.168.14.231'
    description: 'Work laptop (Framework)'

  - hostname: 'tablet'
    short_name: 'tablet'
    ip: '192.168.14.12'
    description: 'Main tablet'

  - hostname: 'nas'
    short_name: 'nas'
    ip: '192.168.14.100'
    description: 'Synology NAS'

vpn_machines:
  - short_name: 'remus'
    public_key: ''
    ip_endpoint: 231
  - short_name: 'lockhart'
    public_key: ''
    ip_endpoint: 11

### RIP ONEPLUS 6, you will be missed ###
# - hostname: 'op6'
    #short_name: 'op6'
    #ip: '192.168.1.13'
    #description: 'Main phone'

  - hostname: 'oppo-x3-lite'
    short_name: 'x3'
    ip: '192.168.14.33'
    description: 'Oppo Find x3 lite'

  - hostname: 'switch'
    short_name: 'switch'
    ip: '192.168.14.14'
    description: 'Main Nintendo Switch'

forwarded_dns_servers:
  - 2a00:f826:8:2::195
  - 2a03:4000:4d:c92:88c0:96ff:fec6:b9d
  - 1.1.1.1
  - 8.8.8.8

#region nginx
nginx_apps:
  - app_name: paperless
    short_name: paper
    port: 8000
  - app_name: jellyfin
    short_name: play
    port: 8096
  - app_name: gitea
    short_name: git
    port: 3000
#endregion
