version: "3.8"

services:
  server:
    image: gitea/gitea:1.15.9
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - router_database
    ports:
      - "127.0.0.1:3000:3000"
      - "22:22"

networks:
  router_database:
    external: true
    name: router_database